### ISSUE TITLE
安装完毕后用test序列做预测时报错

### ISSUE THREAD

**Issue by xiaocainiaooo** [Fzhang1992/human-infecting_virus_finder#1]
python 环境3.7

python predResult.py --query test --output predict_result --file mod_data --kmer 4 --kjob 1 --bjob 1
/wss/anaconda2/envs/py36/lib/python3.7/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
Traceback (most recent call last):
  File "predResult.py", line 78, in <module>
    model.fit(X_train,y_train)
  File "/wss/anaconda2/envs/py36/lib/python3.7/site-packages/imblearn/ensemble/_bagging.py", line 246, in fit
    return self._fit(X, y, self.max_samples, sample_weight=None)
  File "/wss/anaconda2/envs/py36/lib/python3.7/site-packages/sklearn/ensemble/bagging.py", line 375, in _fit
    for i in range(n_jobs))
  File "/wss/anaconda2/envs/py36/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/wss/anaconda2/envs/py36/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/wss/anaconda2/envs/py36/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/wss/anaconda2/envs/py36/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/wss/anaconda2/envs/py36/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/wss/anaconda2/envs/py36/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/wss/anaconda2/envs/py36/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 131, in <listcomp>
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/wss/anaconda2/envs/py36/lib/python3.7/site-packages/sklearn/ensemble/bagging.py", line 116, in _parallel_build_estimators
    estimator.fit((X[indices])[:, features], y[indices])
  File "/wss/anaconda2/envs/py36/lib/python3.7/site-packages/imblearn/pipeline.py", line 238, in fit
    Xt, yt, fit_params = self._fit(X, y, **fit_params)
  File "/wss/anaconda2/envs/py36/lib/python3.7/site-packages/imblearn/pipeline.py", line 176, in _fit
    for step_idx, name, transformer in self._iter(with_final=False):
AttributeError: 'Pipeline' object has no attribute '_iter'

**Comment by Fzhang1992** [comment]
Hi xiaocainiaooo,
The problem look like
https://github.com/scikit-learn-contrib/imbalanced-learn/issues/584
please try update scikit-learn

**Comment by xiaocainiaooo** [comment]
Hello,
I have retested the script by your solution, however i got the same error again. Here are versions of my tools and packages:
anaconda: 4.7.11
python: 3.7.4
pandas: 0.25.0
numpy: 1.15.4
scikit-learn: 0.21.3
imbalanced-learn: 0.5.0
And i think it will better to provide the official version information of your packages for users. Thanks.

**Comment by Fzhang1992** [comment]
Hi xiaocainiaooo,  
Sorry for the error, I updated the software and tested in python 3.7.4 with no error.
Can you download the new version and test it again?
Thank you

**Comment by Fzhang1992** [comment]
Hi xiaocainiaooo,
If you use anaconda, please use "conda install XXXX" to install "numpy", "pandas" and "scikit-learn" package.
This way will avoid these error.

**Comment by xiaocainiaooo** [comment]
Hello,
Thanks for help. Now it can run successfully with the "conda install package_name" command. A nice and useful bioinformatic tool for virus prediction!

**Comment by mengyan-zhou** [comment]
hi,
when I use the following command:

    python /home/Public/software/humanvirusfinder/human-infecting_virus_finder-master/predResult.py --query Humanadenovirus12.fasta --output predict_result --file /home/Public/software/humanvirusfinder/human-infecting_virus_finder-master/mod_data --kmer 4 --kjob 1 --bjob 1

The following error occurs:

Traceback (most recent call last):
  File "/home/Public/software/humanvirusfinder/human-infecting_virus_finder-master/predResult.py", line 42, in <module>
    if line[0] == '>':#save the query name
IndexError: string index out of range

could you help me?
thanks in advance！

**Comment by Fzhang1992** [comment]
I'm guessing there is something wrong with the Humanadenovirus12.fasta. Maybe a row of the query file is empty, this will result in an error. Try replacing \n\n with \n.

**Comment by Fzhang1992** [comment]
I'm guessing there is something wrong with the Humanadenovirus12.fasta.
Maybe a row of the query file is empty, this will result in an error.
我猜你的输入文件中含空行，所以会报错（解决办法：把\n\n替换为\n，我觉得这样应该可以删掉里面的空行）。试试用我发的test文件当做query输入是否会报错。

**Comment by mengyan-zhou** [comment]
hi zhang, 
thanks for your reply!
There is really because  a row of the query file is empty with the Humanadenovirus12.fasta. 
Then I used the test file you sent as the query input, and it worked normally, but when I use other query file, there are no results.

When I use the following command:
python predResult.py --query 1.part_001.fasta --output 6result --file mod_data --kmer 4 --kjob 1 --bjob 1

The following is the output result file:
(there is just a name column.)
Name	Model	Label	Probability
>ZMYSS_k127_1013687 			
>ZMYSS_k127_102985 			
>ZMYSS_k127_103860 			
>ZMYSS_k127_155127 			
>ZMYSS_k127_155622 			
>ZMYSS_k127_17557 			
>ZMYSS_k127_260419 			

The following is output process:
500bp model ready
/home/Public/software/humanvirusfinder/human-infecting_virus_finder-master/predResult.py:114: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pred_result = pred_result.append(pred_data)
/home/Public/software/humanvirusfinder/human-infecting_virus_finder-master/predResult.py:114: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pred_result = pred_result.append(pred_data)
Total running time of the program: 169.52 seconds

How do you solve this?  Thanks in advance！

**Comment by Fzhang1992** [comment]
Maybe there is still something wrong with your input file. The input file
format is the first line is the name, the second line is the sequence, then
repeat.

**Comment by mengyan-zhou** [comment]
My input file format really is the first line is the name, the second line is the sequence.
for example:
>ZMYSS_k127_6798 
TGATGTACTAGAAAAGTCCAAGATTAAGAATCTAGACGAAGCTATCAGTGTAGCTGCTCG
TAGGGTTCGTAAGTTCCACCCCGACGGTCTAGACTTAACTGGATTTGAACGTAACGTAAT
GCGTCGTATTATTCCCTTCTACAGTTGGTTACGTAAGGCTACCCCACTGGTAATTGAAAC
TGCTGTTCTGCGTCCACATATTGCTTTTGCTTATCCAAAGGCGATGACGGAATTGCAGAA
CGCAATGGGAATTCCTCTTGGAGAGAATGCAGGATTTGGTAATCCTTATCCTACTGATGC

**Comment by Fzhang1992** [comment]
try add > behind ZMYSS_k127_6798, like >ZMYSS_k127_6798

mengyan-zhou ***@***.***> 于2022年4月1日周五 21:31写道：

**Comment by mengyan-zhou** [comment]
I add > behind ZMYSS_k127_6798, but I forgot to copy there.
so that's not the reason.
